# Generated by Django 5.1.15 on 2026-09-11 07:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(db_index=True, max_length=20)),
                ('clock_in_time', models.CharField(max_length=50)),
                ('clock_out_time', models.CharField(blank=True, max_length=50, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('duration_formatted', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('device_info', models.TextField(blank=True, null=True)),
                ('location_info', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('COMPLETED', 'Completed'), ('NO_CLOCK_OUT', 'No Clock Out'), ('LATE', 'Late'), ('HALF_DAY', 'Half Day')], default='PRESENT', max_length=20)),
                ('work_session_id', models.CharField(max_length=100, unique=True)),
                ('is_manually_corrected', models.IntegerField(default=0)),
                ('correction_reason', models.TextField(blank=True, null=True)),
                ('corrected_at', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corrected_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_corrections', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='organization.employee')),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('start_time', models.CharField(max_length=50)),
                ('end_time', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('CORRECTED', 'Corrected')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='attendance.attendance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='organization.employee')),
            ],
            options={
                'db_table': 'work_sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='unq_employee_daily_attendance'),
        ),
    ]
